name: Refresh Ads List

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "*/5 * * * *"
  workflow_dispatch:

env:
  GH_OWNER: ${{secrets.GH_OWNER}}
  GH_REPO: ${{secrets.GH_REPO}}
  GH_API_TOKEN: ${{secrets.GH_API_TOKEN}}

jobs:
  refresh_ads_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go run .
